Final version

diff --git a/.github/workflows/genre_crawler.yml b/.github/workflows/genre_crawler.yml
--- a/.github/workflows/genre_crawler.yml
+++ b/.github/workflows/genre_crawler.yml
@@ -60,7 +60,7 @@ jobs:
 
       
       - name: Run genre.py for Batch ${{ matrix.batch_id }}
-        run: python -u source/genre.py ${{ matrix.batch_id }} 10 || echo "Script failed, check logs."
+        run: python -u source/genre.py ${{ matrix.batch_id }} 1000 || echo "Script failed, check logs."
       
       
       - name: Upload CSV Progress
