Update genre_crawler.yml

diff --git a/.github/workflows/genre_crawler.yml b/.github/workflows/genre_crawler.yml
--- a/.github/workflows/genre_crawler.yml
+++ b/.github/workflows/genre_crawler.yml
@@ -34,21 +34,13 @@ jobs:
       contents: write  # Cấp quyền ghi vào repo
 
     steps:
+      - name: Run genre.py with real-time logs
+        run: python -u genre.py || echo "Script failed, check logs."
+
       - name: Check Memory Usage
         run: free -h
 
-      - name: Checkout code
-        uses: actions/checkout@v4
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Set up Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: "3.9"
-
-      - name: Install dependencies
-        run: pip install -r requirements.txt
 
       - name: Run genre.py
         run: python genre.py || echo "Script failed, but no notification needed."
