Update genre_crawler.yml

diff --git a/.github/workflows/genre_crawler.yml b/.github/workflows/genre_crawler.yml
--- a/.github/workflows/genre_crawler.yml
+++ b/.github/workflows/genre_crawler.yml
@@ -67,7 +67,9 @@ jobs:
           
           FILE_PATH="data/vgsales_updated_${{ matrix.batch_id }}.csv"
 
-
+          # Cập nhật repo với phiên bản mới nhất
+          git pull --rebase origin master || echo "⚠️ Pull failed, continuing..."
+          
           # Chỉ add file batch hiện tại
           git add "$FILE_PATH"
 
@@ -97,7 +99,7 @@ jobs:
               echo "✅ Push successful!"
               exit 0
             else
-              SLEEP_TIME=$(shuf -i 0-10 -n 1)  # Random số giây từ 0-10
+              SLEEP_TIME=$(shuf -i 1-10 -n 1)  # Random số giây từ 0-10
               echo "⚠️ Push failed, retrying in $SLEEP_TIME seconds..."
               sleep $SLEEP_TIME
             fi
