Update genre_crawler.yml

diff --git a/.github/workflows/genre_crawler.yml b/.github/workflows/genre_crawler.yml
--- a/.github/workflows/genre_crawler.yml
+++ b/.github/workflows/genre_crawler.yml
@@ -42,7 +42,7 @@ jobs:
         run: pip install -r requirements.txt
 
       - name: Run genre.py for Batch ${{ matrix.batch_id }}
-        run: python -u genre.py ${{ matrix.batch_id }} 3000 || echo "Script failed, check logs."
+        run: python -u genre.py ${{ matrix.batch_id }} 1000 || echo "Script failed, check logs."
 
       
       - name: Save progress to GitHub
