Final crawl version

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -191,7 +191,7 @@ jobs:
   
       
       - name: Run genre.py for Batch ${{ matrix.batch_id }}
-        run: python -u source/genre.py ${{ matrix.batch_id }} 5 || echo "Script failed, check logs."
+        run: python -u source/genre.py ${{ matrix.batch_id }} 3400 || echo "Script failed, check logs."
       
       
       - name: Upload CSV Progress
